# headers and icon 
title: Harry Guajan
info: Future Computer Engineer
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
